#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_HOST=harry@10.0.0.75
readonly TARGET_PATH=/home/harry/pi-demo
readonly TARGET_ARCH=aarch64-unknown-linux-gnu
#readonly TARGET_ARCH=armv7-unknown-linux-gnueabihf
readonly SOURCE_PATH=./target/${TARGET_ARCH}/release/pi-demo

cargo build --release --target=${TARGET_ARCH}
#cross build --release --target=${TARGET_ARCH}


rsync ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}
ssh -t ${TARGET_HOST} ${TARGET_PATH}
